"""The source-supported system map of systemap.

The map gives component claims for source modules, flow claims,
sequence steps and invariants. Source records and review digests record
the support for these claims. Positions come from `systemap place`.
The placement command keeps positions in the model unless `--all` applies.
Pinned cards keep their positions.

The regions divide command operations, source data, the model,
diagram generation and map checks. `systemap check` does consistency
and placement checks. `systemap describe` gives diagram measurements."""

from __future__ import annotations

from dataclasses import replace

import journeys  # sequence data from map/journeys.py

from systemap import (
    Component,
    Container,
    Flow,
    Invariant,
    Layer,
    Meaning,
    Model,
    Region,
)

# Every position, box and the canvas below were written by `systemap place`:
# a card keeps its x and y until `place --all` lays the map out again, a
# card written without them is placed into a free slot of its region, and
# no card is pinned, so `place --all` may move any of them.

CONTAINERS = (
    Container(
        id="outside",
        label="OUTSIDE THE PACKAGE",
        sub="External components",
        box=(16, 16, 190, 644),
        tone="host",
    ),
    Container(
        id="systemap",
        label="SYSTEMAP",
        sub="One CLI process",
        box=(230, 16, 848, 860),
        tone="server",
    ),
)

REGIONS = (
    Region("operate", "OPERATE", (250, 80, 380, 204), container="systemap"),
    Region("gather", "SOURCE DATA", (678, 80, 190, 204), container="systemap"),
    Region("mean", "MODEL", (250, 320, 190, 204), container="systemap"),
    Region("draw", "DIAGRAM", (678, 320, 380, 204), container="systemap"),
    Region("keep", "MAP CHECKS", (250, 560, 380, 296), container="systemap"),
)

COMPONENTS = (
    # ---- outside: the agent authors, the maintainer reviews, CI refuses ----
    Component(
        id="Agent",
        does="Reads the skill. Runs the commands and writes the model. Corrects check errors and records judgement answers.",
        kind="actor",
        container="outside",
        x=36,
        y=596,
    ),
    Component(
        id="CI",
        does="Runs the map check for each pull request. Rejects the pull request if the map is not correct.",
        kind="actor",
        container="outside",
        x=36,
        y=412,
    ),
    Component(
        id="Maintainer",
        does="Examines judgement answers. Corrects model errors and writes the map in a Git commit.",
        kind="actor",
        container="outside",
        x=36,
        y=504,
    ),
    Component(
        id="TypeSafe",
        does="The Jev model through the TypeSafe HTTP API. Gives typed answers about the map if the configuration has a key.",
        kind="actor",
        container="outside",
        x=36,
        y=276,
    ),
    # ---- operate: the commands, the configuration, what init writes ----
    Component(
        id="CLI",
        source_review="4a794a77e08c1042710d479a87c71008f3b069c55c93b1f45b86c5b4326905e5",
        does="Gives commands to make, examine, render and update the map. Map check errors give a nonzero exit code. A second-opinion error can leave the map check report without errors.",
        interface="main(argv) -> exit code: 0 current, 1 failed or stale, 2 unusable",
        implemented_by=("systemap.cli", "systemap.__main__"),
        entry="main",
        region="operate",
        x=460,
        y=120,
    ),
    Component(
        id="Scaffold",
        source_review="bc429c995e012f700e75fae65f3c56bbc731ef285718dc7f3482d937f380d8ad",
        does="Writes the initial configuration, model, output directory and workflow. The model has regions on a grid with spaces between them. Does not replace files.",
        interface="write(root, name, package, roots, ci) -> one line per file",
        implemented_by=("systemap.scaffold",),
        entry="write",
        note="Does not replace files. To change the pinned workflow, write its version in the workflow file.",
        region="operate",
        x=270,
        y=212,
    ),
    Component(
        id="Config",
        source_review="973253b687da768ca81a1a17ddbff9430c0af76a2dab697b044f14e8070404ec",
        does="Reads systemap.toml or [tool.systemap] in pyproject.toml with default values. Finds package roots, test files and source-language settings. Keeps judgement answers and reasons. Rejects unknown keys and entries without reasons.",
        interface="load(root) -> Config; load_model(path) -> (MODEL, MEANING); discover_typescript_roots(root)",
        implemented_by=(
            "systemap.config",
            "systemap.language_config",
            "systemap.typescript_config",
        ),
        entry="load",
        kind="store",
        region="operate",
        x=460,
        y=212,
    ),
    # ---- gather: the mechanical truth ----
    Component(
        id="FactsExtractor",
        source_review="f111731ca2e7308561b234794eed83165d3dcedc47c6900b53a16ace980a0247",
        does="Reads the syntax tree and writes module records. Records public names, imports, test imports and entry points. Identifies TypeScript syntax that it cannot parse as unknown. Reads stored facts through systemap facts.",
        interface="build(cfg) -> facts; drift(fresh, stored) -> facts that are different",
        implemented_by=(
            "systemap.extract",
            "systemap.facts",
            "systemap.language",
            "systemap.typescript",
            "systemap.typescript_surface",
            "systemap.ways_in",
        ),
        entry="build",
        region="gather",
        x=698,
        y=120,
    ),
    Component(
        id="ChangeDetector",
        source_review="c0c5d7e5030f839d472546da6cecd9fb5f52e4df728d9b6479f0c0682f7bf8e6",
        does="Compares source revisions. Shows changed public names, module renames and components that import changed modules. systemap delta gives findings and necessary actions. systemap history shows changes to the software structure through time.",
        interface="compute(cfg, model, base, facts, head) -> change; delta.compute(cfg, model, meaning, base facts, head facts) -> Delta",
        implemented_by=(
            "systemap.change",
            "systemap.delta",
            "systemap.delta_report",
            "systemap.moves",
            "systemap.history",
            "systemap.trend",
        ),
        entry="compute",
        region="gather",
        x=698,
        y=212,
    ),
    Component(
        id="Placer",
        source_review="be9e1a02a4c7aa168c1c2c98ca9277d9dff43752c1f80795e47cb10753ee4f90",
        does="Calculates initial card positions in a grid of regions. Scores region orders with route collisions, route errors, bends and length. Writes positions in map/model.py. With --all, keeps only pinned positions.",
        interface="compute(model) -> Placement; write(path, model, placement)",
        implemented_by=("systemap.place",),
        entry="compute",
        region="operate",
        x=270,
        y=120,
    ),
    # ---- mean: the judgement ----
    Component(
        id="Skill",
        source_review="af77f26bd70216c118f121edf520347182db479067b4c15cbe56d808fef7c33d",
        does="Gives the procedure for the agent: extraction, model draft, check, judgement, render and second examination. Gives completion conditions, output requirements and maintenance instructions. Stores text files and references in the package.",
        interface="files() -> the skill directory; write(dir) -> the installed SKILL.md",
        implemented_by=("systemap.skill",),
        entry="write",
        region="mean",
        x=270,
        y=360,
    ),
    Component(
        id="Model",
        source_review="aa1b19242db7d57c4da6010e19e8dc8530e8809b3733a2524630ec658458b513",
        does="Gives the schema for containers, regions, components, flows, invariants and meaning tables. Does model checks. Sets flow evidence states and source review digests. Loads child maps when a component card opens a map.",
        interface="Model(canvas, containers, regions, components, flows, flow_kinds, invariants) and Meaning(plain, layers, relations, journeys, verbs), exported by map/model.py as MODEL and MEANING",
        implemented_by=(
            "systemap.model",
            "systemap.card_review",
            "systemap",
            "systemap.evidence",
            "systemap.nest",
            "systemap.graph",
        ),
        entry="Model",
        kind="store",
        region="mean",
        x=270,
        y=452,
    ),
    # ---- draw: one generator for every picture ----
    Component(
        id="Router",
        source_review="cc9fcf2931dfa9e8c06ad5a1dd93823912022a4fac819b3d10ff20979c952d7e",
        does="Calculates flow paths through spaces between component cards. Finds paths outside unrelated cards and regions. Calculates label positions and gives errors for route or label collisions.",
        interface="route_all(edges, cards, actors, blocks, regions, region_of, canvas) -> routes; place_labels(routes, widths, height, obstacles, canvas) -> seated labels",
        implemented_by=("systemap.route",),
        entry="route_all",
        region="draw",
        x=698,
        y=452,
    ),
    Component(
        id="Schematic",
        source_review="d6b85718d9e9b2e3bdf467e56480a938f2b377b80a07553a550907742fd7841b",
        does="Makes the SVG diagram. Uses card symbols for component kinds and line colors for layers. Shows connected components and selected sequence steps. Gives controls for layers, map position and zoom.",
        interface="render(model, meaning, theme, facts) -> (svg, detail JSON)",
        implemented_by=(
            "systemap.schematic",
            "systemap.schematic_cards",
            "systemap.schematic_style",
            "systemap.schematic_script",
            "systemap.schematic_relations",
            "systemap.theme",
        ),
        entry="render",
        region="draw",
        x=888,
        y=452,
    ),
    Component(
        id="Page",
        source_review="fd3fa5453367bf8e6d5bd2a7ef44f3b893a66823b3bb4cb8ae9509dc37ba964a",
        does="Makes the map page. Shows model positions, flows, sequences and source records in one inspector. Text view shows the same components and flows. Shows judgement reasons and revision comparisons. Uses no external files.",
        interface="build(cfg, model, meaning, theme, facts, change) -> html",
        implemented_by=(
            "systemap.page",
            "systemap.page_data",
            "systemap.page_assets",
            "systemap.page_script",
            "systemap.page_atlas",
        ),
        entry="build",
        region="draw",
        x=888,
        y=360,
    ),
    Component(
        id="Figures",
        source_review="14c16decae1b5320552be0966da074a75f6ff057688e5e069a05c055a09f9c09",
        does="Makes a figure from the same diagram generator for a document. Shows the system, components in a plan, or a change. Gives an SVG file with a background.",
        interface="make(cfg, model, meaning, theme, facts, mode, components, base, head, caption, layer) -> (html, collisions)",
        implemented_by=("systemap.figure",),
        entry="make",
        region="draw",
        x=698,
        y=360,
    ),
    # ---- keep true: what refuses, and what asks a person ----
    Component(
        id="Check",
        source_review="e3f000dfaf449b2b8c6e68ea8ba688a98374a873f51e0f1e71b3f5dc16dc1151",
        does="Does checks of module coverage, entries, interfaces, TypeScript records, layout, routes, labels, text, meaning and outputs. Gives all findings. Returns exit code 1 if there are errors.",
        interface="run(model, meaning, theme, facts, ignores) -> Result; stale(cfg, tree, fresh=None) -> lines",
        implemented_by=("systemap.check",),
        entry="run",
        region="keep",
        x=270,
        y=692,
    ),
    Component(
        id="Judgement",
        source_review="22d029bd6573f5bdc90644ebc582112bc348bbcd4daf8f772c95aaab5948b229",
        does="Gives findings for examination: single-module components, incorrect groups, missing flow explanations, layers, entry points, imports and TypeScript records. Uses accepted answers and policies. With --strict, returns exit code 1 for findings without answers. systemap suggest gives initial module groups.",
        interface="run(model, meaning, facts, sdks) -> lines; exit 1 with --strict while a line is open",
        implemented_by=(
            "systemap.judgement",
            "systemap.judgement_evidence",
            "systemap.journey_coverage",
            "systemap.suggest",
            "systemap.explain",
        ),
        entry="run",
        region="keep",
        x=270,
        y=600,
    ),
    Component(
        id="SecondOpinion",
        source_review="77c6ec90d782373907369f3c7904ea6f86bec07e12566729ad5821676ef10233",
        does="Sends different questions about the map to Jev. Stores answers in a cache. Can tell a coding agent to read the source and write text. Starts only with a different command. Does not control map checks.",
        interface="run(tree, facts, cfg, jev) -> lines; commands return 1 when an optional request fails",
        implemented_by=(
            "systemap.audit",
            "systemap.jev_cli",
            "systemap.jev",
            "systemap.agent",
            "systemap.journeys",
            "systemap.model_write",
            "systemap.plan",
        ),
        entry="run",
        region="keep",
        x=460,
        y=600,
    ),
    Component(
        id="Describe",
        source_review="c75870ebc2a11c71aade60b350f41db73c9c4dcb3a05951eca3dea9f75ff5e69",
        does="Gives diagram measurements as text: cards per region, path bends and lengths, label positions and layer contents. Gives information for examination. Does not control rules.",
        interface="run(model, meaning, theme, facts) -> lines; describe returns 1 when the program cannot render the model",
        implemented_by=("systemap.describe",),
        entry="run",
        region="keep",
        x=270,
        y=784,
    ),
)

# (from, to, the artifact carried, the kind). control: one part drives
# another; data: an artifact moves; judge: this model's own kind, the loop
# in which the meaning is authored and confirmed.
# Current source snapshots and exact semantic claim digests for reviewed flows.
# A changed source or sentence reopens its flow for judgement.
# fmt: off
_SOURCE_SHA = {
    'systemap.agent': '6ad02602e45cceeb42fb0d212a11d5a5f4766b9b1eb8542cc7d2d7a124b19685',
    'systemap.audit': '83179216c0e7efaad8656ce451884829dbf4a37a9ca3e9e196a40dc22ab1ea9f',
    'systemap.card_review': '1977f0f653a067d44c14d04050937d73f4a2c8319f7c69cd691bc6792eb55081',
    'systemap.change': '383e5edd780b0b3a1a3d17abc1197609e60fca81194883bc07c31779b88fc810',
    'systemap.check': '61fefc71ed6ae84680446fa2a2d78f0f9c66b00b5e7f895291dd576fc623959e',
    'systemap.cli': '6f8025a8cf006ace0e221b2e2f5d3b1f49c4f61b7b9a6d7d91bcbd15942ab6db',
    'systemap.config': 'ca965cca10e3f29685f022843f26bf2a1196b33bafc9bcd4bf6ca7ebfa4e7faa',
    'systemap.delta': '9a2d3eccabf6ab3c9430ef968f6d09e14bfb8f61d8d985452f4f385679ee499b',
    'systemap.delta_report': '4f02d4c346f9a46c14b30207057df26e78206de4ce8d558ebe96f576b4323e50',
    'systemap.describe': '63b42b58e7408a30170f745271babe48d826f848d285f8bf6ccaa043a4d5d6cf',
    'systemap.evidence': '41f466b8f1f482bd54edd788ea649f96fc3833ccb3a2fa11b61f09b50a226f9f',
    'systemap.explain': 'b9c1b6a833d9b92752f9c3cf23e43ba316436b6c308b6bfaea0d88f3682e6cca',
    'systemap.extract': '88656627caebc8941368681eeefa8a7ce69293046035e011e69bc843aac4d522',
    'systemap.facts': 'd3b7cab7a8c468f13443efc58d1df42e6958a0f65c7116fc10da6991a690ca1d',
    'systemap.figure': '20f79f749788e66998fbe867a7b328d2f210ffa06bcbba39908f90c0644c7413',
    'systemap.jev_cli': '21b959de69553bf2818cf204727136186cbdcbaeeefa9804b5e55b0841933867',
    'systemap.journey_coverage': '44d615ed243a6c3a636e16e1d4deeb6562121c93300395d049c1f1f0993bd19d',
    'systemap.journeys': '9939bec6e79dc2813d2081cf8cbd4030b50e2207a46f030c18713b6fe4ad148f',
    'systemap.judgement_evidence': '743ce431edd1e507c9b0fecd073a6cdd5d5d537e8e8c9cf2530917089c80dd9c',
    'systemap.judgement': '745a0d1871fd28377afc9d6acc30216ae31ffb40b1cae26d3edf2ac8fd28be53',
    'systemap.model': 'c932400b182ad6a8ad1d9d0d4ea1fafd7bef7c4558856a89766bf9752965a158',
    'systemap.nest': '3208e3d99fff532e59aaadc5d8308391212e2e48e5d59d3d2143035225907e03',
    'systemap.page': '0dd46e0411b558f81539149812db4425725f0b64537a5d9d6384a7ac003f883d',
    'systemap.place': '93a9261e4c84f20a35a47b4f9fe585707e182bdd1a04f5d4dac62e156809815e',
    'systemap.route': 'd1c63831efae5150cc529347b971125168bd02e31016fc89608df466cd6b00f5',
    'systemap.scaffold': '94740a7aacedfba884504500ad8d5aeffa7c6ab5f02ec469eba284b6ec8be281',
    'systemap.schematic': '57b720f7c2887151608474b4f364b9989e8d17e129d21542d63127320eaf4e84',
    'systemap.skill': '71bde7489e07dd6f2555e01b059e52a53c1742fb3e962c581f52a8dec64d901e',
    'systemap.page_data': '3d4141cc124f0e56644ac2618195cc8f7103686bf1f43bbae5c19ffc83e63b4e',
}

_FLOW_REVIEWS = {
    'Skill -> SecondOpinion': ('systemap.skill systemap.agent', 'ffd264d80eb4bb6a2db6fd365d848e41cf21b152bb9e756bb38dfcf2d245ba9f'),
    'CLI -> Scaffold': ('systemap.cli systemap.scaffold', '38b5fb77430365a30169a16e865809d026574e2e0f95501a9d1d3fbb7268beec'),
    'CLI -> Placer': ('systemap.cli systemap.place', 'e389e353780d5df2cb641fd5cd3fad4034c09b9600f533a5ac6ff94778936cd2'),
    'CLI -> Skill': ('systemap.cli systemap.skill', '1fe7138715176b72502a61395d2f1c33272c0a9d0c9207d197bc24fcd07608ce'),
    'CLI -> FactsExtractor': ('systemap.cli systemap.extract systemap.facts', 'c60ab3c45f18c73e62e93aef18f85e0f008461466321be4ceaca28760647b4a1'),
    'CLI -> ChangeDetector': ('systemap.cli systemap.change systemap.delta systemap.delta_report systemap.figure', '6dbad7439d5da8a3560db25c844e2e9a444a489b348987a436e48c1470bd9715'),
    'CLI -> Check': ('systemap.cli systemap.check', '91aea6cf576bee0db812da12b573fa9e3df4d7decc3a0b0f3d7eb14bcd33c7ad'),
    'CLI -> Page': ('systemap.cli systemap.page', 'd8f0850c72db3cc920cac3d4f8c7381c34c038832bb3f26415bdf61e7e9af3d2'),
    'CLI -> Figures': ('systemap.cli systemap.figure', '97286cc0de48942863a27ebef7ec9e2a24cb858e64ea6849affd20a096af9ab8'),
    'CLI -> Judgement': ('systemap.cli systemap.judgement', 'cd82dedcfc314c87c54d0be806f9cbf71342d6c67ee2d3d8217b4f3395d5e483'),
    'CLI -> Describe': ('systemap.cli systemap.describe', '37a945d0799f78139428563168915cfe01a062245af946f802b0e17ebba917c1'),
    'CLI -> SecondOpinion': ('systemap.cli systemap.jev_cli', 'a877b643ee2df94022275153af427609bb6cf94e19ab66e9162cbf5610997625'),
    'Check -> Page': ('systemap.check systemap.page', 'e134c80f5fb9c5931cc8e78e7cf3689cf40460b4c38256f19f0852a578ce2d98'),
    'Check -> Figures': ('systemap.check systemap.figure', '390f4dd7e404f9709039c178305bd9c4ba9b50df4b8b7a7247aa22f8b3434eaf'),
    'Check -> ChangeDetector': ('systemap.check systemap.delta', 'f4e03421fffd6da5ec858dd42a7fd0a8afa680c2da47e3061a7949c983164f40'),
    'Config -> CLI': ('systemap.config systemap.cli', '910330f62ce33ad8801edd36c67b6f740e65195d91bf64c411e00b4edd7c3f75'),
    'Config -> FactsExtractor': ('systemap.config systemap.extract', '21c916dd89d0ce20d3990255eb52f2958ac0c293161bd37e4d99be04dd2bfc0a'),
    'Config -> ChangeDetector': ('systemap.config systemap.change', 'd0a1cdb664f3120c4aa2a63a0e2e06c76c4de7095e1783d1b8c6cb875863fb49'),
    'Config -> Page': ('systemap.config systemap.page', '550b88850702ffb62e468d640a541617194d304476526ad29cdaea621b8e28d5'),
    'Config -> Figures': ('systemap.config systemap.figure systemap.cli', 'd762269f179eade7fbff47ea47d84842221d4ffcf47fdf8ad1c2490e23a7202a'),
    'Config -> Check': ('systemap.config systemap.check systemap.cli', '46957dd0fcd5a3ec528b85416f99bd7741124e536b9cd4d419d7696522a2694f'),
    'Config -> Judgement': ('systemap.config systemap.judgement systemap.judgement_evidence systemap.cli', '415373f58af09ccd36a1399e5868117aab48bcc9cfbfb3fecb8dd7873505e269'),
    'Config -> SecondOpinion': ('systemap.config systemap.jev_cli systemap.audit', 'ce4679c0eb01aa37f07006db7cbf1b24400c77ab1dfd74419a7bcdc3596d3aa9'),
    'FactsExtractor -> SecondOpinion': ('systemap.jev_cli systemap.audit', '98d9a6b3e3319ceb78a0204f4f8db1c73b2c3af15e18eb39aaf36e73c25a557f'),
    'SecondOpinion -> ChangeDetector': ('systemap.jev_cli systemap.cli systemap.delta', '9969643a7f111a4e2669ee6386d5852cc1844b16599fc11ba997b9fccf1faf3c'),
    'Judgement -> SecondOpinion': ('systemap.journey_coverage systemap.journeys', 'e2a0338a72b87fe10ab1685c68b7925ced5dfc606fdef3861997fe0fd8cfb761'),
    'SecondOpinion -> Describe': ('systemap.journeys systemap.describe', 'ab2404f74734c529acfb5798faba10362306ea40a664d0b96bf1061e4115021d'),
    'FactsExtractor -> Describe': ('systemap.extract systemap.describe', '0a1403e29534709747f509c4fb2c6e5d724976af583375dde60d4014df8569d5'),
    'Scaffold -> Model': ('systemap.scaffold systemap.cli', '41e1d924d76d1edf80bd88349c94acf3988b1990da77af4d54a51bdfff4b98ee'),
    'FactsExtractor -> Check': ('systemap.extract systemap.check', '3b29df945e640e8e57b96bb617c6c0832560a868a290be0314c4f3ba6f527a51'),
    'FactsExtractor -> Schematic': ('systemap.extract systemap.schematic systemap.evidence', 'eecbb468025bf89bdc129b103013ed5d0ccb1018946c50180b5ad8ad7d2fb921'),
    'FactsExtractor -> Judgement': ('systemap.judgement systemap.journey_coverage', 'd98c92e37c779d11aee2c865d530332618884a8e508293f1fdc977c535a53247'),
    'FactsExtractor -> ChangeDetector': ('systemap.extract systemap.change', 'aeeacc92c1adc9f2bca4dfd3ee2570e9341db1dce46fca54e176ae4393df1982'),
    'ChangeDetector -> Page': ('systemap.change systemap.cli systemap.page', 'c111d1c6e5c840ef6c566525d22d884d9c880ef3e47b0a4815715768509006e2'),
    'ChangeDetector -> Figures': ('systemap.change systemap.figure', 'a0c73d860f8736f18770e3d3e5bef47f94c19fcf15512ed15d3411f4471b45d0'),
    'Model -> Placer': ('systemap.model systemap.place', '58555f409b8b4ffa47d2d5c507d2e84a78b4ad3e54f4907dd341c9c354c45d10'),
    'Placer -> Model': ('systemap.place', '871179bb5d44bc1520042fb490607844a4f27613d7e0cf9c64cd887190acf065'),
    'Model -> FactsExtractor': ('systemap.model systemap.extract', '54439c3951f301f91f6cb34a34c6fca6a28bf385fa6710cfec18b2ea9fcc33eb'),
    'Model -> ChangeDetector': ('systemap.model systemap.card_review systemap.change systemap.delta', '721c07bdf70572e059ff14d643bde4c8338206d1eb6aca24914c29be08c0dc32'),
    'Model -> Schematic': ('systemap.model systemap.schematic', '1da68d8790030f26473f92a5e87464b6e0b0ed45aa607f812a2b2eb43a264b3e'),
    'Model -> Check': ('systemap.model systemap.check', '7e8131de6d95128792420a156da252441300909138923d6108b4e66b83638663'),
    'Model -> CLI': ('systemap.model systemap.nest systemap.cli', 'a1476494d9bbe7348f957b0642c91d045d79c7ad3b035ca2ae0424c5412c00dd'),
    'Config -> Model': ('systemap.config systemap.nest', '9277a32e4a9295866140a9bf2908710cc9a493bac91c7e51a316bfd3509201f2'),
    'Model -> Page': ('systemap.model systemap.page', '6a353a794b28bf1c35d4048fca8ec7919f2495ae123b32e1711da59430134b60'),
    'Model -> Figures': ('systemap.model systemap.figure', 'a6c21421441d4dbdf9f6d542e97a1d430f5e96b9e0886b24ae210b9976a26ede'),
    'Model -> Describe': ('systemap.model systemap.describe', 'db7d81158c04511652b300ef520f43d63b9ac2e309a1f190c95b90c370ad19c4'),
    'Router -> Schematic': ('systemap.route systemap.schematic', '295123aeb76a438d9384115be3d68b17cb6e25292cf04329e1dc74d8166dea92'),
    'Router -> Describe': ('systemap.route systemap.describe', '03c671467b988b448b3d7b28fa2d7072a5e8800f3e421beeeaaef8ae756e0658'),
    'Router -> Placer': ('systemap.route systemap.place', '66fd40ebd373494d61d21837a3607e905c6cb82698d710afe2764c6662bc523b'),
    'Schematic -> Placer': ('systemap.schematic systemap.place', '3fec25e26595e803c6f8257d9827a3fcb2766842b24db0a4452276117f02a8ea'),
    'Placer -> Describe': ('systemap.place systemap.describe', 'fc44a64c970c5b658446a4045565577718820d58b5570cec4405b74be2e42abe'),
    'Schematic -> Page': ('systemap.schematic systemap.page', 'f0062784874c305491524d444a6ae48a388c3cadae90003152d59f6f5e29c749'),
    'Schematic -> Figures': ('systemap.schematic systemap.figure', '5b8e3c9f7b1ed5b3825fc39516a641db395bc175da327e521fc03137ec585343'),
    'Schematic -> Check': ('systemap.schematic systemap.check', '6d6ffdc28151384719d625fbf9e5a2350d2bafe222c84862842ccb717b54acf2'),
    'Schematic -> Describe': ('systemap.schematic systemap.describe', '7e55c2ae06cf8f8ece344efd6574c8a4d20d2e260ba8eec32fd2867b7320d8b0'),
    'Model -> Judgement': ('systemap.model systemap.judgement', '9172b8e1e49dbda2300c6c45fa478925fcb3e5efe55ccde6903a7d01db11e15a'),
    'Judgement -> Check': ('systemap.explain systemap.check', 'd1a74cca2fcd7f8a2068cb8ad652976234f70b313ad57be0c35cb7efa8437666'),
    'Model -> SecondOpinion': ('systemap.model systemap.audit', 'a584bbc52c30cea9087b67eea05a1578718206f9db6502b14dbe483a6f01ff89'),
    'Judgement -> ChangeDetector': ('systemap.judgement systemap.explain systemap.delta systemap.delta_report', '635dc1267e2c7f60a011c8f74bb9d0d57fc4f0b3699870c0a99973e2a4aed8ae'),
    'FactsExtractor -> Page': ('systemap.extract systemap.page_data', '7457dc4b890eeffa8a45025e43d28cbab8c40190270b48500cc54d650334b54d'),
    'Judgement -> Page': ('systemap.judgement systemap.page_data', '2aa45cca1e666e51ced40a26ec1909c4d36aad1cec06c796b942b261635e45ce'),
}
# fmt: on


def _reviewed(flow: Flow) -> Flow:
    record = _FLOW_REVIEWS.get(f"{flow.src} -> {flow.dst}")
    if record is None:
        return flow
    modules, digest = record
    refs = tuple(f"{module}@{_SOURCE_SHA[module]}" for module in modules.split())
    return replace(flow, source_refs=refs, review_digest=digest)


FLOWS = tuple(
    _reviewed(flow)
    for flow in (
        # control: who drives whom
        Flow("Agent", "CLI", "commands", "control"),
        Flow("CI", "CLI", "check", "control"),
        Flow("CLI", "Scaffold", "init", "control"),
        Flow("CLI", "Placer", "place", "control"),
        Flow("CLI", "Skill", "init, skill", "control"),
        Flow("CLI", "FactsExtractor", "extract, facts", "control"),
        Flow("CLI", "Check", "check", "control"),
        Flow("CLI", "ChangeDetector", "--base, delta", "control"),
        Flow("CLI", "Page", "render", "control"),
        Flow("CLI", "Figures", "figure", "control"),
        Flow("CLI", "Judgement", "judgement", "control"),
        Flow("CLI", "Describe", "describe", "control"),
        Flow("CLI", "SecondOpinion", "model commands", "control"),
        Flow("Check", "Page", "render to compare", "control"),
        Flow("Check", "Figures", "render to compare", "control"),
        Flow("Check", "ChangeDetector", "interface rule", "control"),
        # data: what moves, and where it goes
        Flow("Config", "CLI", "settings", "data"),
        Flow("Config", "FactsExtractor", "package roots", "data"),
        Flow("Config", "ChangeDetector", "roots, test directories", "data"),
        Flow("Config", "Page", "name, paths", "data"),
        Flow("Config", "Figures", "figures table", "data"),
        Flow("Config", "Check", "ignores", "data"),
        Flow("Config", "Judgement", "answers, sdks", "data"),
        Flow("Config", "SecondOpinion", "answers, model, cache", "data"),
        Flow("FactsExtractor", "SecondOpinion", "map.json", "data"),
        Flow("SecondOpinion", "TypeSafe", "questions", "data"),
        Flow("TypeSafe", "SecondOpinion", "typed answers", "data"),
        Flow("SecondOpinion", "ChangeDetector", "Jev module matches", "data"),
        Flow("Judgement", "SecondOpinion", "uncovered entry points", "data"),
        Flow("SecondOpinion", "Describe", "uncovered entry points", "data"),
        Flow("FactsExtractor", "Describe", "entry points", "data"),
        Flow("Scaffold", "Model", "initial model", "data"),
        Flow("FactsExtractor", "Check", "map.json", "data"),
        Flow("FactsExtractor", "Schematic", "map.json", "data"),
        Flow("FactsExtractor", "Judgement", "entry points", "data"),
        Flow("FactsExtractor", "ChangeDetector", "public surfaces", "data"),
        Flow("FactsExtractor", "Page", "source records", "data"),
        Flow("ChangeDetector", "Page", "change map", "data"),
        Flow("ChangeDetector", "Figures", "change", "data"),
        Flow("Model", "Placer", "cards, flows", "data"),
        Flow("Placer", "Model", "positions", "data"),
        Flow("Model", "FactsExtractor", "claims", "data"),
        Flow("Model", "ChangeDetector", "claims", "data"),
        Flow("Model", "Schematic", "topology, meaning", "data"),
        Flow("Model", "Check", "model", "data"),
        Flow("Model", "CLI", "loaded map", "data"),
        Flow("Config", "Model", "path and model", "data"),
        Flow("Model", "Page", "layers", "data"),
        Flow("Model", "Figures", "layers", "data"),
        Flow("Model", "Describe", "readings", "data"),
        Flow("Router", "Schematic", "routes, labels", "data"),
        Flow("Router", "Describe", "gutters, seats", "data"),
        Flow("Router", "Placer", "routes, seats", "data"),
        Flow("Schematic", "Placer", "geometry", "data"),
        Flow("Placer", "Describe", "region order, score", "data"),
        Flow("Schematic", "Page", "svg, detail", "data"),
        Flow("Schematic", "Figures", "svg", "data"),
        Flow("Schematic", "Check", "geometry", "data"),
        Flow("Schematic", "Describe", "geometry", "data"),
        Flow("Describe", "Agent", "diagram measurements", "data"),
        Flow("Page", "Maintainer", "the page", "data"),
        Flow("Check", "Agent", "the fix", "data"),
        Flow("ChangeDetector", "Agent", "change history", "data"),
        Flow("Check", "CI", "verdict", "data"),
        Flow("Judgement", "ChangeDetector", "judgement data", "data"),
        # judge: where the meaning comes from, and who confirms it
        Flow("Skill", "Agent", "procedure", "judge"),
        Flow("Skill", "SecondOpinion", "language policy", "data"),
        Flow("Agent", "Model", "map/model.py", "judge"),
        Flow("Maintainer", "Model", "corrections", "judge"),
        Flow("Model", "Judgement", "model", "judge"),
        Flow("Judgement", "Check", "finding explanations", "judge"),
        Flow("Judgement", "Page", "findings and reasons", "judge"),
        Flow("Judgement", "Agent", "second-pass list", "judge"),
        Flow("Judgement", "Maintainer", "judgement answers", "judge"),
        Flow("Model", "SecondOpinion", "cards, sentences", "judge"),
        Flow("SecondOpinion", "Agent", "jev lines", "judge"),
    )
)

FLOW_KINDS = ("judge",)

# The rules the repository states about itself, each with its source: the
# current documentation, source guard clauses and regression tests.
INVARIANTS = (
    Invariant(
        1,
        "Do not show code or test counts on the page. The map shows system functions, not code quantity (src/systemap/skill/references/schema.md, Component).",
        governs=("Page", "Schematic", "Figures"),
    ),
    Invariant(
        2,
        "A component must have a function that a reader can identify. A module alone does not identify a component (README, What are a component, a flow, and a sequence?).",
        governs=("Model", "Skill", "Judgement"),
    ),
    Invariant(
        3,
        "Flow lines show relationships. Each flow must have an explanation (src/systemap/skill/references/schema.md, Flow).",
        governs=("Model", "Schematic"),
    ),
    Invariant(
        4,
        "The map shows code in the repository. Each module in a component claim must be in the facts. The map is not a plan (src/systemap/check.py, check_entry).",
        governs=("Model", "Check", "FactsExtractor"),
    ),
    Invariant(
        5,
        "Keep positions in the model. systemap place or a person writes positions. The check rejects layout errors (src/systemap/skill/references/layout.md, Component positions and routes).",
        governs=("Model", "Placer", "Router", "Check", "Schematic"),
    ),
    Invariant(
        6,
        "The agent writes the model. The check rejects errors. The maintainer examines the model (README, How do you install systemap?).",
        governs=("Agent", "Check", "Maintainer", "Judgement"),
    ),
    Invariant(
        7,
        "Make the map with more than one examination. A second examination is necessary (src/systemap/skill/SKILL.md, The loop).",
        governs=("Skill", "Judgement", "Agent"),
    ),
    Invariant(
        8,
        "The page has no external file requests or dependencies (src/systemap/page.py, build).",
        governs=("Page",),
    ),
    Invariant(
        9,
        "Reject unknown configuration keys. Do not ignore them (src/systemap/config.py, load: 'unknown key').",
        governs=("Config",),
    ),
    Invariant(
        10,
        "Each ignored module must have a reason (tests/test_coverage.py: test_ignore_without_reason_is_a_config_error).",
        governs=("Config", "Check"),
    ),
    Invariant(
        11,
        "check and judgement do not use the network. A different Jev command sends requests only with a key (src/systemap/jev_cli.py, docstring).",
        governs=("Check", "Judgement", "SecondOpinion"),
    ),
    Invariant(
        12,
        "Use ASD-STE100 Issue 9 for all names and all text that a person reads (AGENTS.md, Language requirement).",
        governs=(
            "Agent",
            "Maintainer",
            "CLI",
            "Scaffold",
            "Config",
            "FactsExtractor",
            "ChangeDetector",
            "Placer",
            "Skill",
            "Model",
            "Router",
            "Schematic",
            "Page",
            "Figures",
            "Check",
            "Judgement",
            "SecondOpinion",
            "Describe",
        ),
    ),
)

MODEL = Model(
    canvas=(1094, 892),
    containers=CONTAINERS,
    regions=REGIONS,
    components=COMPONENTS,
    flows=FLOWS,
    flow_kinds=FLOW_KINDS,
    invariants=INVARIANTS,
)

# ---- meaning: the plain words, the layers, one sentence per flow ---------

PLAIN = {
    "Agent": "The coding agent",
    "CI": "The CI process",
    "Maintainer": "The maintainer",
    "CLI": "The commands",
    "Scaffold": "The initial files",
    "Placer": "The card positions",
    "Config": "The configuration",
    "FactsExtractor": "The source records",
    "ChangeDetector": "The source comparison",
    "Skill": "The agent procedure",
    "Model": "The map schema",
    "Router": "The flow paths",
    "Schematic": "The map diagram",
    "Page": "The map page",
    "Figures": "The document figures",
    "Check": "The map checks",
    "Judgement": "The review findings",
    "Describe": "The diagram measurements",
    "SecondOpinion": "The external advice",
    "TypeSafe": "The Jev service",
}

# The page derives Structure, System context, Data flow and Control flow.
# This model has one reading of its own: the loop in which the meaning is
# authored, questioned and confirmed.
LAYERS = (
    Layer(
        id="judge",
        label="Map review",
        question="Who writes and examines the model?",
        sub="Model instructions, claims and examination",
    ),
)

LAYER_OF_KIND = {"judge": "judge"}

# One sentence per flow, keyed "from -> to".
_RELATIONS = {
    "Agent -> CLI": "The agent uses the commands for all operations. It does not import the package.",
    "CI -> CLI": "The initial workflow runs the check for each push and pull request.",
    "CLI -> Scaffold": "init writes the initial files. It does not replace files.",
    "CLI -> Skill": "init installs the bundled skill directory. The skill command installs it again on request.",
    "CLI -> Placer": "place writes initial card positions. With --all, it keeps only pinned cards. describe calculates positions without file changes.",
    "Router -> Placer": "The placer uses the router to score selected region orders. It selects the order with the fewest collisions and route errors. Bends and path length also contribute to the score.",
    "Schematic -> Placer": "The placer uses the diagram geometry to score layouts. Header measurements set the minimum box sizes.",
    "Placer -> Describe": "Describe reads the region order and diagram score. It shows the number of orders in the layout search.",
    "CLI -> FactsExtractor": "extract and refresh make facts for the configured package roots. facts reads the stored result by module or view.",
    "CLI -> ChangeDetector": "render --base and figure --base compare source revisions. delta compares map facts at two commits.",
    "CLI -> Check": "check does all rules and gives each error with a necessary action. refresh does the same checks before the render operation.",
    "CLI -> Page": "render and refresh make the page from the facts and model.",
    "CLI -> Figures": "figure writes one figure. refresh writes all figures in the configuration.",
    "CLI -> Judgement": "judgement gives findings for examination or answers. With --strict, it returns exit code 1 if findings without answers stay.",
    "CLI -> Describe": "describe makes the same diagram as the page and shows its measurements.",
    "Check -> Page": "The output check makes the page from stored facts. It compares the result with the stored page.",
    "Check -> Figures": "The output check makes all configured figures. It compares each result with the stored figure.",
    "Check -> ChangeDetector": "delta uses the interface rule from check to find errors when an interface name is missing.",
    "Config -> CLI": "The configuration gives the package roots, model path and output paths to the commands.",
    "Config -> FactsExtractor": "The package roots and test directories set the source files that the extractor reads.",
    "Config -> ChangeDetector": "The package roots and test directories identify changed module files and test files.",
    "Config -> Page": "The page reads its title, footer paths and outside-region label from the configuration.",
    "Config -> Figures": "The [[figures]] table gives the figures, output modes and output files for refresh.",
    "Config -> Check": "An ignore entry removes a module from the coverage check. The entry must have a reason.",
    "Config -> Judgement": "Judgement uses accepted answers with evidence or explicit policies. The [facts] model_sdks list changes the SDK names for its checks.",
    "Scaffold -> Model": "init writes an initial model with regions and no component cards. The agent must add components from the facts before check completes without errors.",
    "FactsExtractor -> Check": "The check uses facts for module coverage, entry points and output comparison.",
    "FactsExtractor -> Schematic": "The diagram uses facts for source states, entry modules and flow evidence.",
    "FactsExtractor -> Judgement": "Judgement finds entry points without sequences and imports between components without flows.",
    "FactsExtractor -> ChangeDetector": "The change detector uses the extractor parser for public names at each revision.",
    "ChangeDetector -> Page": "With --base, the page shows source changes and components that import changed modules. Imports do not show program execution or effects.",
    "ChangeDetector -> Figures": "The change detector gives changed components and components with import connections for a revision comparison. A plan figure reads component IDs directly.",
    "Model -> Placer": "The placer reads component cards, regions and flows. It keeps positions in the model. With --all, it keeps only pinned positions.",
    "Placer -> Model": "The placer writes positions, boxes and canvas size in map/model.py. It keeps all other file bytes unchanged.",
    "Model -> FactsExtractor": "The extractor uses model claims to find modules that are no longer in the repository.",
    "Model -> ChangeDetector": "The change detector gives changed modules their component identifiers. It compares recorded source reviews with digests of source and claims.",
    "Model -> Schematic": "The diagram shows model positions and relationships. The flow list shows model text.",
    "Model -> Check": "The check finds model errors before it makes a diagram. It also does module coverage, entry and interface checks.",
    "Model -> CLI": "The commands load the model and meaning through the map tree. They find model errors before the render operation.",
    "Config -> Model": "The map tree reads the model path from the configuration. The loader validates MODEL and MEANING against their schema.",
    "Model -> Page": "The page uses model components, layers, sequences and invariants for its controls and text.",
    "Model -> Figures": "The figure uses model components and layers to select the diagram and caption.",
    "Model -> Describe": "Describe reads model components, flows, regions and layers to give diagram measurements.",
    "Router -> Schematic": "The router gives paths and label positions. It gives route and label errors with necessary actions.",
    "Router -> Describe": "Describe shows spaces between cards and the number of label positions in each space.",
    "Schematic -> Page": "The page contains the SVG and JSON data for the interaction script.",
    "FactsExtractor -> Page": "The page shows stored source records for a selected component. Imports show connections, not evidence for the flow explanation.",
    "Judgement -> Page": "The page keeps exact finding identifiers and accepted answer explanations from judgement.",
    "Schematic -> Figures": "A figure contains the same SVG in an HTML figure element or as an SVG image.",
    "Schematic -> Check": "The check makes the diagram and reads its geometry: paths, labels and text sizes.",
    "Schematic -> Describe": "describe makes the diagram and reads geometry for regions, flows, spaces and layers.",
    "Describe -> Agent": "After refresh, the agent reads diagram measurements if it cannot open the page.",
    "Page -> Maintainer": "The maintainer opens the page and examines layers and sequences. Map position and zoom controls show diagram data.",
    "Check -> Agent": "Each error has a necessary action. The agent changes the model until coverage and layout checks give no errors.",
    "Check -> CI": "Exit code 1 rejects the pull request. The message gives the necessary command.",
    "Skill -> SecondOpinion": "The configured coding-agent request reads the packaged language policy. The request and cache key contain that policy.",
    "Skill -> Agent": "The skill gives the procedure, schema, example, second examination and output requirements to the agent.",
    "Agent -> Model": "The agent writes module groups, flows, explanations, sequences and invariants in map/model.py.",
    "Maintainer -> Model": "The maintainer corrects model errors. The maintainer controls the model after examination.",
    "Model -> Judgement": "Judgement finds model decisions for examination.",
    "Judgement -> SecondOpinion": "Judgement has one rule for entry-point sequence coverage. The sequence writer uses this rule to find entry points without sequences.",
    "Judgement -> ChangeDetector": "Delta uses judgement answer rules and import groups. Its report uses explanations for finding kinds.",
    "SecondOpinion -> Describe": "Describe reads the entry points without sequences from the sequence writer. It shows the first entry points in this list.",
    "FactsExtractor -> Describe": "Describe uses the entry-point labels from the extractor.",
    "ChangeDetector -> Agent": "delta gives change findings with necessary actions. history shows intervals with the largest changes first, with the commits for each interval.",
    "Judgement -> Check": "Judgement stores explanations for finding kinds. The check uses these explanations to give reasons and necessary actions.",
    "Judgement -> Agent": "During the second examination, the agent examines each import between components and each entry point without a sequence. It changes the model or records answers.",
    "Judgement -> Maintainer": "The maintainer examines each judgement answer. The agent must give the findings for this examination.",
    "CLI -> SecondOpinion": "audit, journeys, plan, triage and --jev run model commands. These commands use Jev or a configured coding agent. check and judgement do not call external services.",
    "Config -> SecondOpinion": "The configuration gives the model, answer cache and answers for Jev findings.",
    "FactsExtractor -> SecondOpinion": "The facts give module docstrings, public names, imports and source lines for each question.",
    "SecondOpinion -> TypeSafe": "The command sends one typed question through HTTPS with the Jev key. It sends no requests without a key.",
    "TypeSafe -> SecondOpinion": "Jev gives a probability or choice with a distribution. The cache stores each answer by model release and question.",
    "SecondOpinion -> ChangeDetector": "For delta --jev, Jev examines module pairs without a rule-based match. Delta uses these answers for additional module moves.",
    "Model -> SecondOpinion": "Questions use the model components, flow explanations, flows and invariants.",
    "SecondOpinion -> Agent": "The agent gets Jev findings for correction or answers. If the configuration has a coding-agent command, the agent also gets text questions.",
}
RELATIONS = {(k.split(" -> ")[0], k.split(" -> ")[1]): v for k, v in _RELATIONS.items()}

VERBS = {
    "control": ("operates", "receives control from"),
    "data": ("gives data to", "reads data from"),
    "judge": ("gives findings to", "reads findings from"),
}

VERB_OVERRIDES = {
    ("Config", "CLI"): ("gives settings to", "reads settings from"),
    ("Scaffold", "Model"): ("writes", "uses initial files from"),
    ("Placer", "Model"): ("writes positions in", "receives positions from"),
    ("Skill", "Agent"): ("gives instructions to", "reads instructions from"),
    ("Agent", "Model"): ("writes", "receives text from"),
    ("Maintainer", "Model"): ("corrects", "receives corrections from"),
    ("Judgement", "Agent"): ("gives findings to", "reads findings from"),
    ("Judgement", "Maintainer"): ("gives answers to", "examines answers from"),
    ("Schematic", "Page"): ("gives SVG to", "uses SVG from"),
    ("Schematic", "Figures"): ("gives SVG to", "uses SVG from"),
    ("Page", "Maintainer"): ("gives a diagram to", "reads the diagram from"),
    ("Config", "Check"): ("gives ignore entries to", "reads ignore entries from"),
    ("Check", "Agent"): ("gives errors to", "reads errors from"),
    ("Describe", "Agent"): ("gives measurements to", "reads measurements from"),
    ("Check", "CI"): ("gives results to", "reads results from"),
    ("Check", "Page"): ("compares output from", "gives output to"),
    ("Check", "Figures"): ("compares output from", "gives output to"),
    ("Check", "ChangeDetector"): ("gives rules to", "uses rules from"),
}

JOURNEYS = journeys.JOURNEYS

MEANING = Meaning(
    plain=PLAIN,
    layers=LAYERS,
    layer_of_kind=LAYER_OF_KIND,
    relations=RELATIONS,
    journeys=JOURNEYS,
    verbs=VERBS,
    verb_overrides=VERB_OVERRIDES,
)
